/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VillagesRouteImport } from './routes/villages'
import { Route as TourismRouteImport } from './routes/tourism'
import { Route as TerritoriesRouteImport } from './routes/territories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as NewsRouteImport } from './routes/news'
import { Route as InvestRouteImport } from './routes/invest'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VillagesSlugRouteImport } from './routes/villages_.$slug'
import { Route as TerritoriesSlugRouteImport } from './routes/territories_.$slug'

const VillagesRoute = VillagesRouteImport.update({
  id: '/villages',
  path: '/villages',
  getParentRoute: () => rootRouteImport,
} as any)
const TourismRoute = TourismRouteImport.update({
  id: '/tourism',
  path: '/tourism',
  getParentRoute: () => rootRouteImport,
} as any)
const TerritoriesRoute = TerritoriesRouteImport.update({
  id: '/territories',
  path: '/territories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestRoute = InvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VillagesSlugRoute = VillagesSlugRouteImport.update({
  id: '/villages_/$slug',
  path: '/villages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TerritoriesSlugRoute = TerritoriesSlugRouteImport.update({
  id: '/territories_/$slug',
  path: '/territories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/history': typeof HistoryRoute
  '/invest': typeof InvestRoute
  '/news': typeof NewsRoute
  '/people': typeof PeopleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/territories': typeof TerritoriesRoute
  '/tourism': typeof TourismRoute
  '/villages': typeof VillagesRoute
  '/territories/$slug': typeof TerritoriesSlugRoute
  '/villages/$slug': typeof VillagesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/history': typeof HistoryRoute
  '/invest': typeof InvestRoute
  '/news': typeof NewsRoute
  '/people': typeof PeopleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/territories': typeof TerritoriesRoute
  '/tourism': typeof TourismRoute
  '/villages': typeof VillagesRoute
  '/territories/$slug': typeof TerritoriesSlugRoute
  '/villages/$slug': typeof VillagesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/history': typeof HistoryRoute
  '/invest': typeof InvestRoute
  '/news': typeof NewsRoute
  '/people': typeof PeopleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/territories': typeof TerritoriesRoute
  '/tourism': typeof TourismRoute
  '/villages': typeof VillagesRoute
  '/territories_/$slug': typeof TerritoriesSlugRoute
  '/villages_/$slug': typeof VillagesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/history'
    | '/invest'
    | '/news'
    | '/people'
    | '/sitemap.xml'
    | '/territories'
    | '/tourism'
    | '/villages'
    | '/territories/$slug'
    | '/villages/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/history'
    | '/invest'
    | '/news'
    | '/people'
    | '/sitemap.xml'
    | '/territories'
    | '/tourism'
    | '/villages'
    | '/territories/$slug'
    | '/villages/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/history'
    | '/invest'
    | '/news'
    | '/people'
    | '/sitemap.xml'
    | '/territories'
    | '/tourism'
    | '/villages'
    | '/territories_/$slug'
    | '/villages_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  HistoryRoute: typeof HistoryRoute
  InvestRoute: typeof InvestRoute
  NewsRoute: typeof NewsRoute
  PeopleRoute: typeof PeopleRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TerritoriesRoute: typeof TerritoriesRoute
  TourismRoute: typeof TourismRoute
  VillagesRoute: typeof VillagesRoute
  TerritoriesSlugRoute: typeof TerritoriesSlugRoute
  VillagesSlugRoute: typeof VillagesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/villages': {
      id: '/villages'
      path: '/villages'
      fullPath: '/villages'
      preLoaderRoute: typeof VillagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourism': {
      id: '/tourism'
      path: '/tourism'
      fullPath: '/tourism'
      preLoaderRoute: typeof TourismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/territories': {
      id: '/territories'
      path: '/territories'
      fullPath: '/territories'
      preLoaderRoute: typeof TerritoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest': {
      id: '/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof InvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villages_/$slug': {
      id: '/villages_/$slug'
      path: '/villages/$slug'
      fullPath: '/villages/$slug'
      preLoaderRoute: typeof VillagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/territories_/$slug': {
      id: '/territories_/$slug'
      path: '/territories/$slug'
      fullPath: '/territories/$slug'
      preLoaderRoute: typeof TerritoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  HistoryRoute: HistoryRoute,
  InvestRoute: InvestRoute,
  NewsRoute: NewsRoute,
  PeopleRoute: PeopleRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TerritoriesRoute: TerritoriesRoute,
  TourismRoute: TourismRoute,
  VillagesRoute: VillagesRoute,
  TerritoriesSlugRoute: TerritoriesSlugRoute,
  VillagesSlugRoute: VillagesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
